<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Quotix.Updater</AssemblyName>
    <RootNamespace>Quotix.Updater</RootNamespace>
    <Company>Grafdustin</Company>
    <Authors>Grafdustin</Authors>
    <Copyright>Copyright (C) 2026 Grafdustin</Copyright>
    <ApplicationIcon>..\Resources\app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Net.Http" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48"
                      Version="1.0.3"
                      PrivateAssets="all" />
  </ItemGroup>
</Project>
