<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>Quotix.Updater</AssemblyName>
    <RootNamespace>Quotix.Updater</RootNamespace>
    <Company>Grafdustin</Company>
    <Authors>Grafdustin</Authors>
    <Copyright>Copyright (C) 2026 Grafdustin</Copyright>
    <ApplicationIcon>..\Resources\app.ico</ApplicationIcon>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
